#!/bin/bash

MYSQL_HOST=<YOUR-DATABASE-HOSTNAME>
MYSQL_PORT=3306
MYSQL_USERNAME=admin
MYSQL_PASSWORD=<YOUR-DATABASE-PASSWORD>

mysql -h"${MYSQL_HOST}" -P"${MYSQL_PORT}" -u"${MYSQL_USERNAME}" -p"${MYSQL_PASSWORD}"
